const { PrismaClient, Prisma } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

const categories = [
  { name: "Phone Essentials", slug: "phone-essentials" },
  { name: "Laptop Studio", slug: "laptop-studio" },
  { name: "Creator Kits", slug: "creator-kits" },
  { name: "Audio & Wearables", slug: "audio-wear" },
  { name: "Print Packs", slug: "print-packs" },
  { name: "Data Bundles", slug: "data-bundles" },
  { name: "Office Essentials", slug: "office-essentials" },
  { name: "Event Visuals", slug: "event-visuals" },
];

const products = [
  {
    name: "Aurora Phone Grip",
    slug: "aurora-phone-grip",
    categorySlug: "phone-essentials",
    price: "48",
    salePrice: "38",
    stock: 120,
    type: "PHYSICAL",
    variants: [{ name: "Color", options: ["Midnight", "Sand", "Emerald"] }],
    specs: { Material: "Silicone", Weight: "20g" },
    media: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Pulse USB-C Hub",
    slug: "pulse-usb-c-hub",
    categorySlug: "laptop-studio",
    price: "180",
    salePrice: "160",
    stock: 52,
    type: "PHYSICAL",
    variants: [{ name: "Ports", options: ["6-in-1", "8-in-1"] }],
    specs: { Ports: "USB-C, HDMI, USB-A", Warranty: "12 months" },
    media: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Creator Light Kit",
    slug: "creator-light-kit",
    categorySlug: "creator-kits",
    price: "320",
    salePrice: "280",
    stock: 26,
    type: "PHYSICAL",
    variants: [{ name: "Kit", options: ["Solo", "Studio"] }],
    specs: { Brightness: "1200 lumens", Power: "USB-C" },
    media: [
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Studio Beat Headset",
    slug: "studio-beat-headset",
    categorySlug: "audio-wear",
    price: "260",
    stock: 38,
    type: "PHYSICAL",
    variants: [{ name: "Finish", options: ["Graphite", "Pearl"] }],
    specs: { Battery: "32 hours", NoiseCancel: "Active" },
    media: [
      "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Merch Flyer Template Pack",
    slug: "merch-flyer-template-pack",
    categorySlug: "print-packs",
    price: "120",
    salePrice: "90",
    stock: 500,
    type: "DIGITAL",
    digitalUrl: "https://example.com/downloads/merch-flyer-pack",
    specs: { Files: "PSD, AI", Pages: "18" },
    media: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Social Brand Kit",
    slug: "social-brand-kit",
    categorySlug: "creator-kits",
    price: "150",
    stock: 400,
    type: "DIGITAL",
    digitalUrl: "https://example.com/downloads/social-brand-kit",
    specs: { Templates: "30", Format: "Canva + Figma" },
    media: [
      "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Desk Flow Planner",
    slug: "desk-flow-planner",
    categorySlug: "office-essentials",
    price: "95",
    stock: 85,
    type: "PHYSICAL",
    specs: { Pages: "180", Cover: "Hardback" },
    media: [
      "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Launch Day Event Pack",
    slug: "launch-day-event-pack",
    categorySlug: "event-visuals",
    price: "210",
    salePrice: "180",
    stock: 240,
    type: "DIGITAL",
    digitalUrl: "https://example.com/downloads/launch-day-pack",
    specs: { Assets: "24", Format: "PSD" },
    media: [
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Swift Data Voucher",
    slug: "swift-data-voucher",
    categorySlug: "data-bundles",
    price: "75",
    stock: 300,
    type: "DIGITAL",
    digitalUrl: "https://example.com/downloads/data-voucher",
    specs: { Volume: "5GB", Validity: "30 days" },
    media: [
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Minimal Laptop Sleeve",
    slug: "minimal-laptop-sleeve",
    categorySlug: "laptop-studio",
    price: "140",
    stock: 64,
    type: "PHYSICAL",
    variants: [{ name: "Size", options: ["13 inch", "15 inch"] }],
    specs: { Material: "Felt", Color: "Stone" },
    media: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Grip & Charge Duo",
    slug: "grip-and-charge-duo",
    categorySlug: "phone-essentials",
    price: "110",
    stock: 75,
    type: "PHYSICAL",
    variants: [{ name: "Bundle", options: ["Grip + Cable", "Grip + Cable + Adapter"] }],
    specs: { Cable: "USB-C", Adapter: "20W" },
    media: [
      "https://images.unsplash.com/photo-1496171367470-9ed9a91ea931?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    name: "Signature Event Badges",
    slug: "signature-event-badges",
    categorySlug: "event-visuals",
    price: "65",
    stock: 180,
    type: "DIGITAL",
    digitalUrl: "https://example.com/downloads/signature-badges",
    specs: { Templates: "12", Format: "AI" },
    media: [
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80",
    ],
  },
];

const dataBundles = [
  {
    network: "mtn",
    name: "MTN Data 1GB",
    price: "4.90",
    volume: "1GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 2GB",
    price: "9.90",
    volume: "2GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 3GB",
    price: "15.00",
    volume: "3GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 4GB",
    price: "20.00",
    volume: "4GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 5GB",
    price: "25.00",
    volume: "5GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 6GB",
    price: "29.00",
    volume: "6GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 7GB",
    price: "34.00",
    volume: "7GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 8GB",
    price: "38.00",
    volume: "8GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 10GB",
    price: "47.00",
    volume: "10GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 12GB",
    price: "56.10",
    volume: "12GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 15GB",
    price: "68.20",
    volume: "15GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "mtn",
    name: "MTN Data 20GB",
    price: "92.40",
    volume: "20GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "mtn-data",
    badge: "MTN",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/MTN_Logo.svg",
  },
  {
    network: "telecel",
    name: "Telecel Data 5GB",
    price: "26.40",
    volume: "5GB",
    validity: "Anytime",
    segment: "Data",
    tag: "telecel-data",
    badge: "Telecel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Telecel_logo.svg",
  },
  {
    network: "telecel",
    name: "Telecel Data 10GB",
    price: "46.20",
    volume: "10GB",
    validity: "Anytime",
    segment: "Data",
    tag: "telecel-data",
    badge: "Telecel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Telecel_logo.svg",
  },
  {
    network: "telecel",
    name: "Telecel Data 15GB",
    price: "66.00",
    volume: "15GB",
    validity: "Anytime",
    segment: "Data",
    tag: "telecel-data",
    badge: "Telecel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Telecel_logo.svg",
  },
  {
    network: "telecel",
    name: "Telecel Data 20GB",
    price: "85.80",
    volume: "20GB",
    validity: "Anytime",
    segment: "Data",
    tag: "telecel-data",
    badge: "Telecel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Telecel_logo.svg",
  },
  {
    network: "telecel",
    name: "Telecel Data 25GB",
    price: "107.80",
    volume: "25GB",
    validity: "Anytime",
    segment: "Data",
    tag: "telecel-data",
    badge: "Telecel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Telecel_logo.svg",
  },
  {
    network: "telecel",
    name: "Telecel Data 30GB",
    price: "127.60",
    volume: "30GB",
    validity: "Anytime",
    segment: "Data",
    tag: "telecel-data",
    badge: "Telecel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Telecel_logo.svg",
  },
  {
    network: "telecel",
    name: "Telecel Data 40GB",
    price: "166.10",
    volume: "40GB",
    validity: "Anytime",
    segment: "Data",
    tag: "telecel-data",
    badge: "Telecel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Telecel_logo.svg",
  },
  {
    network: "telecel",
    name: "Telecel Data 50GB",
    price: "203.50",
    volume: "50GB",
    validity: "Anytime",
    segment: "Data",
    tag: "telecel-data",
    badge: "Telecel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Telecel_logo.svg",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 1GB",
    price: "4.95",
    volume: "1GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 2GB",
    price: "9.90",
    volume: "2GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 3GB",
    price: "15.40",
    volume: "3GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 4GB",
    price: "19.80",
    volume: "4GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 5GB",
    price: "24.20",
    volume: "5GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 6GB",
    price: "26.40",
    volume: "6GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 7GB",
    price: "30.80",
    volume: "7GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 8GB",
    price: "35.20",
    volume: "8GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 10GB",
    price: "42.90",
    volume: "10GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 12GB",
    price: "52.80",
    volume: "12GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 15GB",
    price: "66.00",
    volume: "15GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
  {
    network: "airteltigo",
    name: "AirtelTigo iShare 20GB",
    price: "86.90",
    volume: "20GB",
    validity: "Anytime",
    segment: "iShare",
    tag: "airteltigo-data",
    badge: "AirtelTigo",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/AirtelTigo_logo.png",
  },
];

const toDecimal = (value) => new Prisma.Decimal(value);

async function main() {
  const adminEmail = process.env.ADMIN_SEED_EMAIL?.toLowerCase();
  const adminPassword = process.env.ADMIN_SEED_PASSWORD;
  const adminName = process.env.ADMIN_SEED_NAME || "Boss Admin";
  const adminPhone = process.env.ADMIN_SEED_PHONE || null;

  const categoryMap = {};
  for (const category of categories) {
    const created = await prisma.category.upsert({
      where: { slug: category.slug },
      update: { name: category.name, parentId: category.parentId ?? null },
      create: {
        name: category.name,
        slug: category.slug,
        parentId: category.parentId ?? null,
      },
    });
    categoryMap[category.slug] = created.id;
  }

  for (const product of products) {
    const categoryId = categoryMap[product.categorySlug];
    if (!categoryId) continue;

    await prisma.product.upsert({
      where: { slug: product.slug },
      update: {
        name: product.name,
        price: toDecimal(product.price),
        salePrice: product.salePrice ? toDecimal(product.salePrice) : null,
        stock: product.stock,
        type: product.type,
        categoryId,
        variants: product.variants ?? null,
        media: product.media ?? null,
        specs: product.specs ?? null,
        digitalUrl: product.digitalUrl ?? null,
        active: true,
      },
      create: {
        name: product.name,
        slug: product.slug,
        price: toDecimal(product.price),
        salePrice: product.salePrice ? toDecimal(product.salePrice) : null,
        stock: product.stock,
        type: product.type,
        categoryId,
        variants: product.variants ?? null,
        media: product.media ?? null,
        specs: product.specs ?? null,
        digitalUrl: product.digitalUrl ?? null,
        active: true,
      },
    });
  }

  await prisma.dataBundle.deleteMany({});

  for (const bundle of dataBundles) {
    await prisma.dataBundle.create({
      data: {
        network: bundle.network,
        name: bundle.name,
        price: toDecimal(bundle.price),
        volume: bundle.volume,
        validity: bundle.validity,
        segment: bundle.segment ?? null,
        tag: bundle.tag ?? null,
        badge: bundle.badge ?? null,
        logoUrl: bundle.logoUrl ?? null,
      },
    });
  }

  if (adminEmail && adminPassword) {
    const passwordHash = await bcrypt.hash(adminPassword, 10);
    await prisma.user.upsert({
      where: { email: adminEmail },
      update: {
        name: adminName,
        phone: adminPhone,
        role: "ADMIN",
        passwordHash,
      },
      create: {
        email: adminEmail,
        name: adminName,
        phone: adminPhone,
        role: "ADMIN",
        passwordHash,
      },
    });
    console.log(`✅ Seed admin ready: ${adminEmail}`);
  } else {
    console.log("ℹ️ ADMIN_SEED_EMAIL/ADMIN_SEED_PASSWORD not set. Skipping admin seed.");
  }

  console.log("✅ Seed complete: categories + products ready.");
}

main()
  .catch((error) => {
    console.error("Seed failed", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
